// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiww_acxRjYYWWJsfyS9lBGfXar0LSV3g',
    appId: '1:625019248944:web:d3affd90b67be9b22568f5',
    messagingSenderId: '625019248944',
    projectId: 'alumni-3fb4d',
    authDomain: 'alumni-3fb4d.firebaseapp.com',
    storageBucket: 'alumni-3fb4d.firebasestorage.app',
    measurementId: 'G-YDZC25HLCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Uixieh7FqcVctpjHa-J-QrjoZt5C3oo',
    appId: '1:625019248944:android:d4d20f3f94fddce22568f5',
    messagingSenderId: '625019248944',
    projectId: 'alumni-3fb4d',
    storageBucket: 'alumni-3fb4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi_eoJlL0S8b8BL6vql-u5rcN36DHovfI',
    appId: '1:625019248944:ios:56c148234f5e4efe2568f5',
    messagingSenderId: '625019248944',
    projectId: 'alumni-3fb4d',
    storageBucket: 'alumni-3fb4d.firebasestorage.app',
    iosBundleId: 'com.example.alumniSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi_eoJlL0S8b8BL6vql-u5rcN36DHovfI',
    appId: '1:625019248944:ios:56c148234f5e4efe2568f5',
    messagingSenderId: '625019248944',
    projectId: 'alumni-3fb4d',
    storageBucket: 'alumni-3fb4d.firebasestorage.app',
    iosBundleId: 'com.example.alumniSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiww_acxRjYYWWJsfyS9lBGfXar0LSV3g',
    appId: '1:625019248944:web:bd79d41f811f6e082568f5',
    messagingSenderId: '625019248944',
    projectId: 'alumni-3fb4d',
    authDomain: 'alumni-3fb4d.firebaseapp.com',
    storageBucket: 'alumni-3fb4d.firebasestorage.app',
    measurementId: 'G-NHV1VRGTW5',
  );
}
